#ifndef ERRORS_H
#define ERRORS_H

#define ERROR_NONE 0
#define ERROR_HASH_CREATION_FAILED 1
#define ERROR_TLV_MALLOC 2
#define ERROR_TLV_FILE_OPEN 3
#define ERROR_NO_TLV_FILE 4
#define ERROR_TLV_FILE_TOO_SMALL 5
#define ERROR_TLV_BUFFER_ALLOCATION_FAIL 6
#define ERROR_TOKEN_CREATION_FAILED 7
#define ERROR_TLV_FORMAT 8
#define ERROR_HASH_NOT_SAVED 9
#define ERROR_HASH_NOT_FOUND 10
#define ERROR_TLV_FILE_READ 11

#endif